#cloud-config
users:
  - default
system_info:
  default_user:
    name: ubuntu
    lock_passwd: false
    ssh_authorized_keys: ${ssh_authorized_key}
password: RANDOM
chpasswd:
  expire: false
disable_root: false
ssh_pwauth: yes
hostname: ${hostname}
fqdn: ${hostname}.${domain}
manage_etc_hosts: true
random_seed: # Add uniqueness to created instances
  file: /dev/urandom
  command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
  command_required: true
packages: [vim, tar, zip, gzip, curl, wget]
package_upgrade: true # Upgrade system
power_state: # Reboot if required after upgrade
  delay: 10
  mode: reboot
  condition: test -f /var/run/reboot-required
